server:
  port: 8002
spring:
  application:
    name: edu-user-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.41:3306/edu_user?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: Fy-7545247
  redis:
    host: 192.168.3.41
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}